source("renv/activate.R")
library(here)
library(Zelig)
library(compiler)
library(psych)
library(LaplacesDemon)
library(MASS)
library(rmarkdown)
library(ezknitr)
library(cowplot)
library(ggpubr)
library(linguisticsdown)
library(summarytools)
library(gam)
library(tidyr)
library(ggplot2)
library(matrixStats)
library(readr)

cat("Welcome to Subsampling in Logistic Regression for the Skin Segmentation data,
    when there is no certain model to describe the data.")
