---
title: "Article"
author: "Amalan"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,fig.width = 12,fig.height = 6,message = FALSE,warning = FALSE)
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(LaplacesDemon)
library(xtable)
library(flextable)
library(grid)
library(cowplot)
library(linguisticsdown)
library(ggpubr)

load(here("Identical_r0","Generate_Big_Data","Scaled.RData"))

P_list<-list()
Temp_Plot<-list()
remove(Original_Data,Choice,Nc_size,Replicates,Subsample_Size)
```


```{r load Non Identical Data}
Model_Data<-list()
Model_Accuracy<-list()

for (j in 1:length(All_Models)) 
{
  # Random Sampling
  load(here("Non_Identical_r0","Summary","Classical","Data","Efficiency",
            "Random_Sampling.RData"))
  
  RS_MSE<-data.frame("Method"="Random Sampling","Subsample_Size"=Full_MSE[[j]][,1],
                     "MSE"=Full_MSE[[j]][,2])
  RS_ACC<-data.frame("Method"="Random Sampling","Subsample_Size"=Full_Accuracy[[j]][,1],
                     "MSE"=Full_Accuracy[[j]][,2])
  
  remove(Full_Bias,Full_EMSE,Full_MSE,Full_Info,Full_VAR,Full_Accuracy)
  
  # RE Random Sampling
  load(here("Non_Identical_r0","Summary","Classical","Data","Efficiency",
            "RE_Random_Sampling.RData"))
  
  RE_RS_MSE<-data.frame("Method"="RE Random Sampling","Subsample_Size"=Full_MSE[[j]][,1],
                        "MSE"=Full_MSE[[j]][,2])
  RE_RS_ACC<-data.frame("Method"="RE Random Sampling","Subsample_Size"=Full_Accuracy[[j]][,1],
                        "MSE"=Full_Accuracy[[j]][,2])
  
  remove(Full_Bias,Full_EMSE,Full_MSE,Full_Info,Full_VAR,Full_Accuracy)
  
  # OSMAC
  load(here("Identical_r0","Summary","Classical","Data","Efficiency",
            "OSMAC.RData"))
  
  colnames(Full_MSE[[j]])<-colnames(RS_MSE)
  colnames(Full_Accuracy[[j]])<-colnames(RS_ACC)
  
  # All elements
  All_MSE<-rbind(RS_MSE,RE_RS_MSE,Full_MSE[[j]])
  All_ACC<-rbind(RS_ACC,RE_RS_ACC,Full_Accuracy[[j]])
  
  colnames(All_MSE)[3]<-"Estimated Values"
  colnames(All_ACC)[3]<-"Estimated Values"
  
  Final_Data_Identical_r0<-rbind(cbind(Metric="MSE",All_MSE),
                                 cbind(Metric="Average Accuracy",All_ACC))
  
  Final_Data_Identical_r0$Method<-recode(Final_Data_Identical_r0$Method,
                                         'OSMAC mMSE'="Optimal subsampling mMSE",
                                         'OSMAC mVc'="Optimal subsampling mVc",
                                         'OSMAC mMSE Model Free'="Model Robust subsampling mMSE",
                                         'OSMAC mVc Model Free'="Model Robust subsampling mVc")
  
  # All Colors
  Selected_All<-c("Model Robust subsampling mMSE",
                  "Model Robust subsampling mVc",
                  "Optimal subsampling mMSE",
                  "Optimal subsampling mVc",
                  "Random Sampling")
  # Colors_All<-c("#88CCEE","#0033cc",
  #               "#ff4d4d","#cc0000",
  #               "#006600")
  Colors_All<-c("darkgreen","green",
                "#cc0000","#ff578a",
                "black")
  
  Final_Data<-Final_Data_Identical_r0
  
  Model_Data[[j]]<-Final_Data[(Final_Data$Method %in% Selected_All) & (Final_Data$Metric == "MSE"),]
  Model_Accuracy[[j]]<-Final_Data[(Final_Data$Method %in% Selected_All) & (Final_Data$Metric == "Average Accuracy"),]
  
  Final_Data[(Final_Data$Method %in% Selected_All) & (Final_Data$Metric == "MSE"),] %>%
    ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Method))+
    geom_point(size=1.75)+geom_line(size=1)+
    scale_color_manual(values=Colors_All)+
    theme_light()+xlab("Sub sample size")+
    ggtitle("Simulated MSE")+
    ylab("Estimated Values")
  
  Final_Data[(Final_Data$Method %in% Selected_All) & (Final_Data$Metric == "Average Accuracy"),] %>%
    ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Method))+
    geom_point(size=1.75)+geom_line(size=1)+
    scale_color_manual(values=Colors_All)+
    theme_light()+xlab("Sub sample size")+
    ggtitle("Average Accuracy")+
    ylab("Estimated Values")
}

Combined_MSE<-do.call(rbind,Model_Data)
Combined_Accuracy<-do.call(rbind,Model_Accuracy)

Combined_MSE$Subsample_Size<-Combined_MSE$Subsample_Size-r0
Combined_Accuracy$Subsample_Size<-Combined_Accuracy$Subsample_Size-r0

Theme_special<-function()
{
  theme(axis.text.x = element_text(color = "black",size=12), #, vjust = 0.5
        axis.text.y = element_text(color = "black",size=12), #, vjust = 0.5, hjust=1
        strip.text = element_text(colour = "black",size = 12,face="bold"),
        panel.grid.minor.x = element_blank(),
        axis.title= element_text(color = "black",face = "bold",size = 12),
        legend.text = element_text(color = "black", size=9),
        legend.position = "bottom",
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-1,-1,-1,-1)) 
}

Combined_MSE %>%
  group_by(Metric,Method,Subsample_Size) %>%
  summarise(Sum_MSE=sum(`Estimated Values`)) %>%
  ggplot(.,aes(x=Subsample_Size,y=log(Sum_MSE),color=Method))+
  scale_x_continuous(labels =unique(Combined_MSE$Subsample_Size),
                       breaks =unique(Combined_MSE$Subsample_Size)) +
    geom_point(size=1.75)+geom_line(size=1)+
    scale_color_manual(values=Colors_All)+
    theme_bw()+
    xlab("r")+
    ylab("log(Summed SMSE)")+expand_limits(y = 0)+
    scale_y_continuous(breaks = scales::pretty_breaks(n = length(unique(Combined_MSE$Subsample_Size))/2))+
    guides(colour = guide_legend(nrow = 2))+Theme_special()

#ggsave(filename = "RWA_LR_SkinData.pdf",dpi=300,width = 8,height = 6,units = "in")
ggsave(filename = "RWA_LR_SkinData.eps",device="eps",dpi=300,width = 8,height = 6,units = "in")

Theme_special_1<-function()
{
  theme(axis.text.x = element_text(color = "black",size=15,angle=45,hjust=0.75), #, vjust = 0.5
        axis.text.y = element_text(color = "black",size=15), #, vjust = 0.5, hjust=1
        strip.text = element_text(colour = "black",size = 16,face="bold"),
        panel.grid.minor.x = element_blank(),
        axis.title= element_text(color = "black",face = "bold",size = 18),
        legend.text = element_text(color = "black", size=14),
        legend.position = "bottom",
        #legend.margin=margin(0,0,0,0),
        #legend.box.margin=margin(-1,-1,-1,-1))
        legend.key.width=unit(0.04,"npc"),
        legend.margin = margin(), # pre-emptively set zero margins
        legend.spacing.x = unit(0.2, "cm"))
}

Combined_MSE %>%
  filter(!(Method %in% c("Optimal subsampling mVc","Model Robust subsampling mVc"))) %>%
  group_by(Metric,Method,Subsample_Size) %>%
  summarise(Sum_MSE=sum(`Estimated Values`)) %>%
  ggplot(.,aes(x=Subsample_Size,y=log(Sum_MSE),color=Method))+
  scale_x_continuous(labels =unique(Combined_MSE$Subsample_Size),
                       breaks =unique(Combined_MSE$Subsample_Size)) +
    geom_point(size=1.75)+geom_line(size=1)+
    scale_color_manual(values=Colors_All[c(1,3,5)])+
    theme_bw()+
    xlab("r")+
    ylab("log(Summed SMSE)")+expand_limits(y = 0)+
    scale_y_continuous(breaks = scales::pretty_breaks(n = length(unique(Combined_MSE$Subsample_Size))/2))+
    guides(colour = guide_legend(nrow = 2))+Theme_special_1()

ggsave(filename = "Poster_RWA_LR_SkinData.eps",device="eps",dpi=300,width = 8,height = 6,units = "in")


Combined_MSE[Combined_MSE$Method!="Random Sampling",] %>%
  group_by(Metric,Method,Subsample_Size) %>%
  summarise(Sum_MSE=sum(`Estimated Values`)) %>%
  ggplot(.,aes(x=Subsample_Size,y=log(Sum_MSE),color=Method))+
  scale_x_continuous(labels =unique(Combined_MSE$Subsample_Size) ,
                       breaks =unique(Combined_MSE$Subsample_Size) )+
    geom_point(size=1.75)+geom_line(size=1)+
    scale_color_manual(values=Colors_All)+
    theme_bw()+
    xlab("r")+
    ylab("log(Summed SMSE)")+expand_limits(y = 0)+
    scale_y_continuous(breaks = scales::pretty_breaks(n = length(unique(Combined_MSE$Subsample_Size))/2))+
    guides(colour = guide_legend(nrow = 2))+Theme_special()

Combined_Accuracy %>%
  group_by(Metric,Method,Subsample_Size) %>%
  summarise(Sum_Accuracy=mean(`Estimated Values`)) %>%
  ggplot(.,aes(x=Subsample_Size,y=Sum_Accuracy,color=Method))+
  scale_x_continuous(labels =unique(Combined_Accuracy$Subsample_Size),
                       breaks =unique(Combined_Accuracy$Subsample_Size)) +
    geom_point(size=1.75)+geom_line(size=1)+
    scale_color_manual(values=Colors_All)+
    theme_bw()+
    xlab("r")+
    ylab("Average Accuracy of Y")+
    scale_y_continuous(breaks = scales::pretty_breaks(n = length(unique(Combined_Accuracy$Subsample_Size))/2))+
    guides(colour = guide_legend(nrow = 2))+Theme_special()

ggsave(filename = "RWA_LR_SkinData_Accuracy.pdf",dpi=300,width = 8,height = 6,units = "in")
ggsave(filename = "RWA_LR_SkinData_Accuracy.eps",device="eps",dpi=300,width = 8,height = 6,units = "in")

Combined_Accuracy[Combined_Accuracy$Method!="Random Sampling",] %>%
  group_by(Metric,Method,Subsample_Size) %>%
  summarise(Sum_Accuracy=mean(`Estimated Values`)) %>%
  ggplot(.,aes(x=Subsample_Size,y=Sum_Accuracy,color=Method))+
  scale_x_continuous(labels =unique(Combined_Accuracy$Subsample_Size) ,
                       breaks =unique(Combined_Accuracy$Subsample_Size) )+
    geom_point(size=1.75)+geom_line(size=1)+
    scale_color_manual(values=Colors_All)+
    theme_bw()+
    xlab("r")+
    ylab("Average Accuracy of Y")+
    scale_y_continuous(breaks = scales::pretty_breaks(n = length(unique(Combined_Accuracy$Subsample_Size))/2))+
    guides(colour = guide_legend(nrow = 2))+Theme_special()
```

