---
title: "Publication Ready"
author: "Amalan"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,fig.width = 12,fig.height = 6,message = FALSE,warning = FALSE)
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(LaplacesDemon)
library(xtable)
library(flextable)
library(grid)
library(cowplot)
library(linguisticsdown)
library(ggpubr)

load(here("Identical_r0","Generate_Big_Data","Scaled.RData"))

P_list<-list()
Temp_Plot<-list()
remove(Original_Data,Choice,Nc_Size,r0,Replicates,Subsample_Size)
```


```{r load Non Identical Data,fig.width=24,fig.height=6}
Model_Data<-list()
Model_Accuracy<-list()

for (j in 1:length(All_Models)) 
{
  # Random Sampling
  load(here("Non_Identical_r0","Summary","Classical","Data","Efficiency",
            "Random_Sampling.RData"))
  
  RS_Bias<-data.frame("Model"="Random Sampling","Subsample_Size"=Full_Bias[[j]][,1],
                      "Bias"=Full_Bias[[j]][,2])
  RS_EMSE<-data.frame("Model"="Random Sampling","Subsample_Size"=Full_EMSE[[j]][,1],
                      "EMSE"=Full_EMSE[[j]][,2])
  RS_Info<-data.frame("Model"="Random Sampling","Subsample_Size"=Full_Info[[j]][,1],
                      "Info"=Full_Info[[j]][,2])
  RS_MSE<-data.frame("Model"="Random Sampling","Subsample_Size"=Full_MSE[[j]][,1],
                     "MSE"=Full_MSE[[j]][,2])
  RS_VAR<-data.frame("Model"="Random Sampling","Subsample_Size"=Full_VAR[[j]][,1],
                     "VAR"=Full_VAR[[j]][,2])
  RS_ACC<-data.frame("Model"="Random Sampling","Subsample_Size"=Full_Accuracy[[j]][,1],
                     "VAR"=Full_Accuracy[[j]][,2])
  
  remove(Full_Bias,Full_EMSE,Full_MSE,Full_Info,Full_VAR,Full_Accuracy)
  
  # RE Random Sampling
  load(here("Non_Identical_r0","Summary","Classical","Data","Efficiency",
            "RE_Random_Sampling.RData"))
  
  RE_RS_Bias<-data.frame("Model"="RE Random Sampling","Subsample_Size"=Full_Bias[[j]][,1],
                         "Bias"=Full_Bias[[j]][,2])
  RE_RS_EMSE<-data.frame("Model"="RE Random Sampling","Subsample_Size"=Full_EMSE[[j]][,1],
                         "EMSE"=Full_EMSE[[j]][,2])
  RE_RS_Info<-data.frame("Model"="RE Random Sampling","Subsample_Size"=Full_Info[[j]][,1],
                         "Info"=Full_Info[[j]][,2])
  RE_RS_MSE<-data.frame("Model"="RE Random Sampling","Subsample_Size"=Full_MSE[[j]][,1],
                        "MSE"=Full_MSE[[j]][,2])
  RE_RS_VAR<-data.frame("Model"="RE Random Sampling","Subsample_Size"=Full_VAR[[j]][,1],
                        "VAR"=Full_VAR[[j]][,2])
  RE_RS_ACC<-data.frame("Model"="RE Random Sampling","Subsample_Size"=Full_Accuracy[[j]][,1],
                        "VAR"=Full_Accuracy[[j]][,2])
  
  remove(Full_Bias,Full_EMSE,Full_MSE,Full_Info,Full_VAR,Full_Accuracy)
  
  # OSMAC
  load(here("Non_Identical_r0","Summary","Classical","Data","Efficiency",
            "OSMAC.RData"))
  
  ## mMSE
  OSMAC_mMSE_Bias<-data.frame("Model"="OSMAC mMSE","Subsample_Size"=Full_Bias[[j]][Full_Bias[[j]]$Type=="mMSE",2],
                              "Bias"=Full_Bias[[j]][Full_Bias[[j]]$Type=="mMSE",3])
  OSMAC_mMSE_EMSE<-data.frame("Model"="OSMAC mMSE","Subsample_Size"=Full_EMSE[[j]][Full_EMSE[[j]]$Type=="mMSE",2],
                              "EMSE"=Full_EMSE[[j]][Full_EMSE[[j]]$Type=="mMSE",3])
  OSMAC_mMSE_Info<-data.frame("Model"="OSMAC mMSE","Subsample_Size"=Full_Info[[j]][Full_Info[[j]]$Type=="mMSE",2],
                              "Info"=Full_Info[[j]][Full_Info[[j]]$Type=="mMSE",3])
  OSMAC_mMSE_MSE<-data.frame("Model"="OSMAC mMSE","Subsample_Size"=Full_MSE[[j]][Full_MSE[[j]]$Type=="mMSE",2],
                             "MSE"=Full_MSE[[j]][Full_MSE[[j]]$Type=="mMSE",3])
  OSMAC_mMSE_VAR<-data.frame("Model"="OSMAC mMSE","Subsample_Size"=Full_VAR[[j]][Full_VAR[[j]]$Type=="mMSE",2],
                             "VAR"=Full_VAR[[j]][Full_VAR[[j]]$Type=="mMSE",3])
  OSMAC_mMSE_ACC<-data.frame("Model"="OSMAC mMSE","Subsample_Size"=Full_Accuracy[[j]][Full_Accuracy[[j]]$Type=="mMSE",2],
                             "VAR"=Full_Accuracy[[j]][Full_Accuracy[[j]]$Type=="mMSE",3])
  
  ## mVc
  OSMAC_mVc_Bias<-data.frame("Model"="OSMAC mVc","Subsample_Size"=Full_Bias[[j]][Full_Bias[[j]]$Type=="mVc",2],
                             "Bias"=Full_Bias[[j]][Full_Bias[[j]]$Type=="mVc",3])
  OSMAC_mVc_EMSE<-data.frame("Model"="OSMAC mVc","Subsample_Size"=Full_EMSE[[j]][Full_EMSE[[j]]$Type=="mVc",2],
                             "EMSE"=Full_EMSE[[j]][Full_EMSE[[j]]$Type=="mVc",3])
  OSMAC_mVc_Info<-data.frame("Model"="OSMAC mVc","Subsample_Size"=Full_Info[[j]][Full_Info[[j]]$Type=="mVc",2],
                             "Info"=Full_Info[[j]][Full_Info[[j]]$Type=="mVc",3])
  OSMAC_mVc_MSE<-data.frame("Model"="OSMAC mVc","Subsample_Size"=Full_MSE[[j]][Full_MSE[[j]]$Type=="mVc",2],
                            "MSE"=Full_MSE[[j]][Full_MSE[[j]]$Type=="mVc",3])
  OSMAC_mVc_VAR<-data.frame("Model"="OSMAC mVc","Subsample_Size"=Full_VAR[[j]][Full_VAR[[j]]$Type=="mVc",2],
                            "VAR"=Full_VAR[[j]][Full_VAR[[j]]$Type=="mVc",3])
  OSMAC_mVc_ACC<-data.frame("Model"="OSMAC mVc","Subsample_Size"=Full_Accuracy[[j]][Full_Accuracy[[j]]$Type=="mVc",2],
                            "VAR"=Full_Accuracy[[j]][Full_Accuracy[[j]]$Type=="mVc",3])
  
  remove(Full_Bias,Full_EMSE,Full_MSE,Full_Info,Full_VAR,Full_Accuracy)
  
  # OSMAC Model Free
  load(here("Non_Identical_r0","Summary","Classical","Data","Efficiency",
            "OSMAC_MF_Full.RData"))
  
  ## mMSE
  OSMAC_mMSE_MF_Bias<-data.frame("Model"="OSMAC mMSE Model Free","Subsample_Size"=Full_Bias[[j]][Full_Bias[[j]]$Type=="mMSE",2],
                                 "Bias"=Full_Bias[[j]][Full_Bias[[j]]$Type=="mMSE",3])
  OSMAC_mMSE_MF_EMSE<-data.frame("Model"="OSMAC mMSE Model Free","Subsample_Size"=Full_EMSE[[j]][Full_EMSE[[j]]$Type=="mMSE",2],
                                 "EMSE"=Full_EMSE[[j]][Full_EMSE[[j]]$Type=="mMSE",3])
  OSMAC_mMSE_MF_Info<-data.frame("Model"="OSMAC mMSE Model Free","Subsample_Size"=Full_Info[[j]][Full_Info[[j]]$Type=="mMSE",2],
                                 "Info"=Full_Info[[j]][Full_Info[[j]]$Type=="mMSE",3])
  OSMAC_mMSE_MF_MSE<-data.frame("Model"="OSMAC mMSE Model Free","Subsample_Size"=Full_MSE[[j]][Full_MSE[[j]]$Type=="mMSE",2],
                                "MSE"=Full_MSE[[j]][Full_MSE[[j]]$Type=="mMSE",3])
  OSMAC_mMSE_MF_VAR<-data.frame("Model"="OSMAC mMSE Model Free","Subsample_Size"=Full_VAR[[j]][Full_VAR[[j]]$Type=="mMSE",2],
                                "VAR"=Full_VAR[[j]][Full_VAR[[j]]$Type=="mMSE",3])
  OSMAC_mMSE_MF_ACC<-data.frame("Model"="OSMAC mMSE Model Free","Subsample_Size"=Full_Accuracy[[j]][Full_Accuracy[[j]]$Type=="mMSE",2],
                                "VAR"=Full_Accuracy[[j]][Full_Accuracy[[j]]$Type=="mMSE",3])
  
  ## mVc
  OSMAC_mVc_MF_Bias<-data.frame("Model"="OSMAC mVc Model Free","Subsample_Size"=Full_Bias[[j]][Full_Bias[[j]]$Type=="mVc",2],
                                "Bias"=Full_Bias[[j]][Full_Bias[[j]]$Type=="mVc",3])
  OSMAC_mVc_MF_EMSE<-data.frame("Model"="OSMAC mVc Model Free","Subsample_Size"=Full_EMSE[[j]][Full_EMSE[[j]]$Type=="mVc",2],
                                "EMSE"=Full_EMSE[[j]][Full_EMSE[[j]]$Type=="mVc",3])
  OSMAC_mVc_MF_Info<-data.frame("Model"="OSMAC mVc Model Free","Subsample_Size"=Full_Info[[j]][Full_Info[[j]]$Type=="mVc",2],
                                "Info"=Full_Info[[j]][Full_Info[[j]]$Type=="mVc",3])
  OSMAC_mVc_MF_MSE<-data.frame("Model"="OSMAC mVc Model Free","Subsample_Size"=Full_MSE[[j]][Full_MSE[[j]]$Type=="mVc",2],
                               "MSE"=Full_MSE[[j]][Full_MSE[[j]]$Type=="mVc",3])
  OSMAC_mVc_MF_VAR<-data.frame("Model"="OSMAC mVc Model Free","Subsample_Size"=Full_VAR[[j]][Full_VAR[[j]]$Type=="mVc",2],
                               "VAR"=Full_VAR[[j]][Full_VAR[[j]]$Type=="mVc",3])
  OSMAC_mVc_MF_ACC<-data.frame("Model"="OSMAC mVc Model Free","Subsample_Size"=Full_Accuracy[[j]][Full_Accuracy[[j]]$Type=="mVc",2],
                               "VAR"=Full_Accuracy[[j]][Full_Accuracy[[j]]$Type=="mVc",3])
  
  remove(Full_Bias,Full_EMSE,Full_MSE,Full_Info,Full_VAR,Full_Accuracy)
  
  # All elements
  All_Bias<-rbind(RS_Bias,RE_RS_Bias,
                  OSMAC_mMSE_Bias,OSMAC_mVc_Bias,
                  OSMAC_mMSE_MF_Bias,OSMAC_mVc_MF_Bias)
  All_EMSE<-rbind(RS_EMSE,RE_RS_EMSE,
                  OSMAC_mMSE_EMSE,OSMAC_mVc_EMSE,
                  OSMAC_mMSE_MF_EMSE,OSMAC_mVc_MF_EMSE)
  All_MSE<-rbind(RS_MSE,RE_RS_MSE,
                 OSMAC_mMSE_MSE,OSMAC_mVc_MSE,
                 OSMAC_mMSE_MF_MSE,OSMAC_mVc_MF_MSE)
  All_Info<-rbind(RS_Info,RE_RS_Info,
                  OSMAC_mMSE_Info,OSMAC_mVc_Info,
                  OSMAC_mMSE_MF_Info,OSMAC_mVc_MF_Info)
  All_VAR<-rbind(RS_VAR,RE_RS_VAR,
                 OSMAC_mMSE_VAR,OSMAC_mVc_VAR,
                 OSMAC_mMSE_MF_VAR,OSMAC_mVc_MF_VAR)
  All_ACC<-rbind(RS_ACC,RE_RS_ACC,
                 OSMAC_mMSE_ACC,OSMAC_mVc_ACC,
                 OSMAC_mMSE_MF_ACC,OSMAC_mVc_MF_ACC)
  
  All_Objects<-ls()
  remove(list = All_Objects[startsWith(All_Objects,"OSMAC")])
  remove(list = All_Objects[startsWith(All_Objects,"RS")])
  remove(list = All_Objects[startsWith(All_Objects,"RE_RS")])
  
  colnames(All_Bias)[3]<-"Estimated Values"
  colnames(All_EMSE)[3]<-"Estimated Values"
  colnames(All_Info)[3]<-"Estimated Values"
  colnames(All_MSE)[3]<-"Estimated Values"
  colnames(All_VAR)[3]<-"Estimated Values"
  colnames(All_ACC)[3]<-"Estimated Values"
  
  Final_Data_Non_Identical_r0<-rbind(cbind(Metric="Bias",All_Bias),
                                     cbind(Metric="EMSE",All_EMSE),
                                     cbind(Metric="Model Information",All_Info),
                                     cbind(Metric="MSE",All_MSE),
                                     cbind(Metric="Variance",All_VAR),
                                     cbind(Metric="Average Accuracy",All_ACC))
  # Random Sampling
  load(here("Non_Identical_r0","Summary","Classical","Data","Efficiency",
            "Random_Sampling.RData"))
  
  RS_Bias<-data.frame("Model"="Random Sampling","Subsample_Size"=Full_Bias[[j]][,1],
                      "Bias"=Full_Bias[[j]][,2])
  RS_EMSE<-data.frame("Model"="Random Sampling","Subsample_Size"=Full_EMSE[[j]][,1],
                      "EMSE"=Full_EMSE[[j]][,2])
  RS_Info<-data.frame("Model"="Random Sampling","Subsample_Size"=Full_Info[[j]][,1],
                      "Info"=Full_Info[[j]][,2])
  RS_MSE<-data.frame("Model"="Random Sampling","Subsample_Size"=Full_MSE[[j]][,1],
                     "MSE"=Full_MSE[[j]][,2])
  RS_VAR<-data.frame("Model"="Random Sampling","Subsample_Size"=Full_VAR[[j]][,1],
                     "VAR"=Full_VAR[[j]][,2])
  RS_ACC<-data.frame("Model"="Random Sampling","Subsample_Size"=Full_Accuracy[[j]][,1],
                     "VAR"=Full_Accuracy[[j]][,2])
  
  remove(Full_Bias,Full_EMSE,Full_MSE,Full_Info,Full_VAR,Full_Accuracy)
  
  # RE Random Sampling
  load(here("Non_Identical_r0","Summary","Classical","Data","Efficiency",
            "RE_Random_Sampling.RData"))
  
  RE_RS_Bias<-data.frame("Model"="RE Random Sampling","Subsample_Size"=Full_Bias[[j]][,1],
                         "Bias"=Full_Bias[[j]][,2])
  RE_RS_EMSE<-data.frame("Model"="RE Random Sampling","Subsample_Size"=Full_EMSE[[j]][,1],
                         "EMSE"=Full_EMSE[[j]][,2])
  RE_RS_Info<-data.frame("Model"="RE Random Sampling","Subsample_Size"=Full_Info[[j]][,1],
                         "Info"=Full_Info[[j]][,2])
  RE_RS_MSE<-data.frame("Model"="RE Random Sampling","Subsample_Size"=Full_MSE[[j]][,1],
                        "MSE"=Full_MSE[[j]][,2])
  RE_RS_VAR<-data.frame("Model"="RE Random Sampling","Subsample_Size"=Full_VAR[[j]][,1],
                        "VAR"=Full_VAR[[j]][,2])
  RE_RS_ACC<-data.frame("Model"="RE Random Sampling","Subsample_Size"=Full_Accuracy[[j]][,1],
                        "VAR"=Full_Accuracy[[j]][,2])
  
  remove(Full_Bias,Full_EMSE,Full_MSE,Full_Info,Full_VAR,Full_Accuracy)
  
  # OSMAC
  load(here("Identical_r0","Summary","Classical","Data","Efficiency",
            "OSMAC.RData"))
  
  colnames(Full_Bias[[j]])[3]<-colnames(RS_Bias)[3]
  colnames(Full_EMSE[[j]])[3]<-colnames(RS_EMSE)[3]
  colnames(Full_MSE[[j]])[3]<-colnames(RS_MSE)[3]
  colnames(Full_Info[[j]])[3]<-colnames(RS_Info)[3]
  colnames(Full_VAR[[j]])[3]<-colnames(RS_VAR)[3]
  colnames(Full_Accuracy[[j]])[3]<-colnames(RS_ACC)[3]
  
  # All elements
  All_Bias<-rbind(RS_Bias,RE_RS_Bias,Full_Bias[[j]])
  All_EMSE<-rbind(RS_EMSE,RE_RS_EMSE,Full_EMSE[[j]])
  All_MSE<-rbind(RS_MSE,RE_RS_MSE,Full_MSE[[j]])
  All_Info<-rbind(RS_Info,RE_RS_Info,Full_Info[[j]])
  All_VAR<-rbind(RS_VAR,RE_RS_VAR,Full_VAR[[j]])
  All_ACC<-rbind(RS_ACC,RE_RS_ACC,Full_Accuracy[[j]])
  
  colnames(All_Bias)[3]<-"Estimated Values"
  colnames(All_EMSE)[3]<-"Estimated Values"
  colnames(All_Info)[3]<-"Estimated Values"
  colnames(All_MSE)[3]<-"Estimated Values"
  colnames(All_VAR)[3]<-"Estimated Values"
  colnames(All_ACC)[3]<-"Estimated Values"
  
  Final_Data_Identical_r0<-rbind(cbind(Metric="Bias",All_Bias),
                                 cbind(Metric="EMSE",All_EMSE),
                                 cbind(Metric="Model Information",All_Info),
                                 cbind(Metric="MSE",All_MSE),
                                 cbind(Metric="Variance",All_VAR),
                                 cbind(Metric="Average Accuracy",All_ACC))
  
  # All Colors
  Selected_All<-c("OSMAC mMSE","OSMAC mMSE Model Free",
                  "OSMAC mVc","OSMAC mVc Model Free",
                  "Random Sampling")
  Colors_All<-c("#88CCEE","#0033cc",
                "#ff4d4d","#cc0000",
                "#006600")
  
  Final_Data<-rbind(cbind(Data="Identical r0",Final_Data_Identical_r0),
                    cbind(Data="Non Identical r0",Final_Data_Non_Identical_r0))
  
  Model_Data[[j]]<-Final_Data[(Final_Data$Model %in% Selected_All) & (Final_Data$Metric == "MSE"),]
  Model_Accuracy[[j]]<-Final_Data[(Final_Data$Model %in% Selected_All) & (Final_Data$Metric == "Average Accuracy"),]
  
  Final_Data[(Final_Data$Model %in% Selected_All) & (Final_Data$Metric == "MSE"),] %>%
    ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model))+
    geom_point(size=1.75)+geom_line(size=1)+
    scale_color_manual(values=Colors_All)+
    theme_light()+xlab("Sub sample size")+
    ggtitle("Simulated MSE")+
    ylab("Estimated Values")+facet_grid(~Data,scales = "free_y")->p1
  
  Final_Data[(Final_Data$Model %in% Selected_All) & (Final_Data$Metric == "Model Information"),] %>%
    ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model))+
    geom_point(size=1.75)+geom_line(size=1)+
    scale_color_manual(values=Colors_All)+
    theme_light()+xlab("Sub sample size")+
    ggtitle("Model Information")+
    ylab("Estimated Values")+facet_grid(~Data,scales = "free_y")->p2
  
  Final_Data[(Final_Data$Model %in% Selected_All) & (Final_Data$Metric == "Average Accuracy"),] %>%
    ggplot(.,aes(x=Subsample_Size,y=`Estimated Values`,color=Model))+
    geom_point(size=1.75)+geom_line(size=1)+
    scale_color_manual(values=Colors_All)+
    theme_light()+xlab("Sub sample size")+
    ggtitle("Average Accuracy")+
    ylab("Estimated Values")+facet_grid(~Data,scales = "free_y")->p3
  
  P_list[[j]]<-list(p1,p2,p3)
  
  ggarrange(plotlist =P_list[[j]],nrow = 1,common.legend = TRUE)->Temp_Plot[[j]]
  
  annotate_figure(Temp_Plot[[j]],
                  top = paste0("Covariates in the Model :",stringr::str_c(All_Models[[j]],collapse = ",")))->Plot_Temp
  
  print(Plot_Temp)
}
```

```{r, fig.width=12,fig.height=6}
Combined_MSE<-do.call(rbind,Model_Data)
Combined_Accuracy<-do.call(rbind,Model_Accuracy)

Combined_MSE %>%
  filter(Model != "Random Sampling") %>%
  group_by(Data,Metric,Model,Subsample_Size) %>%
  summarise(Sum_MSE=sum(`Estimated Values`,na.rm = TRUE)) %>%
  ggplot(.,aes(x=Subsample_Size,y=Sum_MSE,color=Model))+
    geom_point(size=1.75)+geom_line(size=1)+
    scale_color_manual(values=Colors_All)+
    theme_light()+xlab("Sub sample size")+
    ggtitle("Simulated MSE")+
    ylab("Estimated Values")+facet_grid(~Data,scales = "free_y")

Combined_Accuracy %>%
  #filter(Model != "Random Sampling") %>%
  group_by(Data,Metric,Model,Subsample_Size) %>%
  summarise(Sum_Accuracy=sum(`Estimated Values`,na.rm = TRUE)) %>%
  ggplot(.,aes(x=Subsample_Size,y=Sum_Accuracy,color=Model))+
    geom_point(size=1.75)+geom_line(size=1)+
    scale_color_manual(values=Colors_All)+
    theme_light()+xlab("Sub sample size")+
    ggtitle("Average Accuracy")+
    ylab("Estimated Values")+facet_grid(~Data,scales = "free_y")

```

